sensio_framework_extra:
    request:
        converters: true
        auto_convert: false
    serializer:
         enabled: true
         enable_annotations: true
         name_converter: serializer.name_converter.camel_case_to_snake_case
